server:
  port: 9611

spring:
  application:
    name: java-mianshi
  profiles:
    active: dev

logging:
  config: classpath:logback-spring.xml
  level:
    org.springframework: WARN
    springfox: WARN
    org.mybatis: info
    com.netflix: warn